{% set version = "1.1-7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-wrs2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/WRS2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/WRS2/WRS2_{{ version }}.tar.gz
  sha256: 4720977afe88c5651270d1c566e5bd65906ba2fd8fa5dfe3a4adc9bf1d5de38f

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-mc2d
    - r-plyr
    - r-reshape
  run:
    - r-base
    - r-mass
    - r-mc2d
    - r-plyr
    - r-reshape

test:
  commands:
    - $R -e "library('WRS2')"           # [not win]
    - "\"%R%\" -e \"library('WRS2')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/psychor/
  license: GPL-3.0-only
  summary: A collection of robust statistical methods based on Wilcox' WRS functions. It implements robust t-tests (independent and dependent samples), robust ANOVA (including between-within subject designs), quantile ANOVA, robust correlation, robust mediation, and nonparametric ANCOVA models based on robust location measures.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: WRS2
# Type: Package
# Title: A Collection of Robust Statistical Methods
# Version: 1.0-0
# Date: 2019-06-05
# Authors@R: c(person(given="Patrick", family="Mair", email="mair@fas.harvard.edu", role=c("cre","aut")), person(given="Rand", family="Wilcox", email="rwilcox@usc.edu", role=c("aut")))
# Description: A collection of robust statistical methods based on Wilcox' WRS functions. It implements robust t-tests (independent and dependent samples), robust ANOVA (including between-within subject designs), quantile ANOVA, robust correlation, robust mediation, and nonparametric ANCOVA models based on robust location measures.
# License: GPL-3
# URL: https://r-forge.r-project.org/projects/psychor/
# Imports: MASS, reshape, plyr, stats, graphics, grDevices, utils, mc2d
# Depends: R (>= 3.2.0)
# Suggests: knitr, car, ggplot2, colorspace, mediation, GGally
# VignetteBuilder: knitr
# LazyData: yes
# LazyLoad: yes
# ByteCompile: yes
# NeedsCompilation: yes
# Packaged: 2019-06-05 23:44:33 UTC; root
# Author: Patrick Mair [cre, aut], Rand Wilcox [aut]
# Maintainer: Patrick Mair <mair@fas.harvard.edu>
# Repository: CRAN
# Date/Publication: 2019-06-06 10:19:21 UTC
