# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "i6wc/2SMJQRXPIw8nUOy5m/Y+BQ1yc/cdB0i7z/9qSRFpC8DtfPhtepVeA0/soJxcTsBtLrGJG7cYkIYrB4mLBOTLh8tLsHff6+B43z6GQQU+pATLmyGMo+fFyWTHjulArwuO0kflfKJ9pmCTjiHfFGsSYMolYKQ9zIcUZKs5icgMFLC/MpDmCsaPaT04II90+dvnnghl9obeJU3Uy2zq94dsKNr7TLWysi7CTBuEutqMD0e1nwi3H3wP9xsKhcBx3wcWxuc7Cz74fjnTt0PcWMjco5Bs62WvXog3Kw3Fg+fIR0DomZ6A9GmEncW004HdBuSOSLLnts5i6uCMBnd0FZlCHa+gbDdfjhC5rx74Cba2qZZ4MZ1KqcBG/hb5GtvBajmQ/lL7Ia4k5LHTWrzaLvkKp+zy+0qKKvZMqcQT5btMd3NyWNBONyIvin+cOSZ07FTIQBw1UiBPAQjvIQRMJceCauvPgm/KTDnGrwpaCN8Ekq3j/Usm1Jas89WUTOkGHY6ml2EECVOs/+0QEBP5wXBoE/fNlhkHtQ/hHUViQDg9UiG/nSaxAd3Gg4SaWdbwFfuCi6H+fL/XYlxzfGOMZ5ruD6RrsXXJ8wpoF8+/TYDFq+Xztea+AO/nxBNDex6Eqh50bh4GW1O+pFeEf9R/G7MEAs5VEkwIOf+Oiup5Gg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
