appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: i6wc/2SMJQRXPIw8nUOy5m/Y+BQ1yc/cdB0i7z/9qSRFpC8DtfPhtepVeA0/soJxcTsBtLrGJG7cYkIYrB4mLBOTLh8tLsHff6+B43z6GQQU+pATLmyGMo+fFyWTHjulArwuO0kflfKJ9pmCTjiHfFGsSYMolYKQ9zIcUZKs5icgMFLC/MpDmCsaPaT04II90+dvnnghl9obeJU3Uy2zq94dsKNr7TLWysi7CTBuEutqMD0e1nwi3H3wP9xsKhcBx3wcWxuc7Cz74fjnTt0PcWMjco5Bs62WvXog3Kw3Fg+fIR0DomZ6A9GmEncW004HdBuSOSLLnts5i6uCMBnd0FZlCHa+gbDdfjhC5rx74Cba2qZZ4MZ1KqcBG/hb5GtvBajmQ/lL7Ia4k5LHTWrzaLvkKp+zy+0qKKvZMqcQT5btMd3NyWNBONyIvin+cOSZ07FTIQBw1UiBPAQjvIQRMJceCauvPgm/KTDnGrwpaCN8Ekq3j/Usm1Jas89WUTOkGHY6ml2EECVOs/+0QEBP5wXBoE/fNlhkHtQ/hHUViQDg9UiG/nSaxAd3Gg4SaWdbwFfuCi6H+fL/XYlxzfGOMZ5ruD6RrsXXJ8wpoF8+/TYDFq+Xztea+AO/nxBNDex6Eqh50bh4GW1O+pFeEf9R/G7MEAs5VEkwIOf+Oiup5Gg=}
